<a href="https://colab.research.google.com/github/saithrr/Telecom_X2_SRR/blob/main/Telecom_X2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [17]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv( '/content/drive/MyDrive/datos_procesados.csv')
df. head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,abandono,genero,tiene +60,posee_pareja,posee_dependientes,tiempo_contrato,servicio_telefono,multiples_lineas,tipo_internet,seguridad_online,...,proteccion_dispositivo,soporte_tecnico,streaming_tv,streaming_peliculas,tipo_contrato,factura_digital,metodo_pago,valor_mensal,total_cobrado,gasto_diario
0,No,Femenino,0,Sí,Sí,9,Sí,No,DSL,No,...,No,Sí,Sí,No,Anual,Yes,Cheque enviado por correo,65.6,593.30,2.197407
1,No,Masculino,0,No,No,9,Sí,Sí,DSL,No,...,No,No,No,Sí,Mensual,No,Cheque enviado por correo,59.9,542.40,2.008889
2,Sí,Masculino,0,No,No,4,Sí,No,Fibra óptica,No,...,Sí,No,No,No,Mensual,Yes,Cheque electrónico,73.9,280.85,2.340417
3,Sí,Masculino,1,Sí,No,13,Sí,No,Fibra óptica,No,...,Sí,No,Sí,Sí,Mensual,Yes,Cheque electrónico,98.0,1237.85,3.173974
4,Sí,Femenino,1,Sí,No,3,Sí,No,Fibra óptica,No,...,No,Sí,Sí,No,Mensual,Yes,Cheque enviado por correo,83.9,267.40,2.971111

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   abandono                7043 non-null   object
 1   genero                  7043 non-null   object
 2   tiene +60               7043 non-null   int64
 3   posee_pareja            7043 non-null   object
 4   posee_dependientes      7043 non-null   object
 5   tiempo_contrato         7043 non-null   int64
 6   servicio_telefono       7043 non-null   object
 7   multiples_lineas        7043 non-null   object
 8   tipo_internet           7043 non-null   object
 9   seguridad_online        7043 non-null   object
 10  backup_online           7043 non-null   object
 11  proteccion_dispositivo  7043 non-null   object
 12  soporte_tecnico         7043 non-null   object
 13  streaming_tv            7043 non-null   object
 14  streaming_peliculas     7043 non-null   object
 15  tipo_contrato           7043 non-null   object
 16  factura_digital         7043 non-null   object
 17  metodo_pago             7043 non-null   object
 18  valor_mensal            7043 non-null   float64
 19  total_cobrado           7043 non-null   float64
 20  gasto_diario            7043 non-null   float64
dtypes: float64(3), int64(2), object(16)
memory usage: 1.1+ MB

In [20]:
df.describe()

         tiene +60  tiempo_contrato  valor_mensal  total_cobrado  gasto_diario
count  7043.000000      7043.000000   7043.000000    7043.000000   7043.000000
mean      0.162147        32.371149     64.761692    2279.734304      2.156607
std       0.368612        24.559481     30.090047    2266.794470      1.009022
min       0.000000         0.000000     18.250000       0.000000      0.000000
25%       0.000000         9.000000     35.500000     398.550000      1.188300
50%       0.000000        29.000000     70.350000    1394.550000      2.343333
75%       0.000000        55.000000     89.850000    3786.600000      3.005805
max       1.000000        72.000000    118.750000    8684.800000      4.046667